apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafanadatasource
  namespace: ach
spec:
  datasources:
    - basicAuthUser: internal
      access: proxy
      secureJsonData: {}
      name: prometheus
      url: 'https://prometheus-k8s.openshift-monitoring.svc:9091'
      basicAuthPassword:
        valueFrom:
          secretKeyRef:
              name: prometheus-secret
              key: session_secret
      jsonData:
        timeInterval: 5s
        tlsSkipVerify: true
      basicAuth: true
      version: 1
      type: prometheus
      orgId: 1
  name: prometheus-grafanadatasource.yaml
