---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: data-explore
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'quay.io/guimou/data_explore:latest'
      importPolicy: {}
      referencePolicy:
        type: Source
