apiVersion: serving.knative.dev/v1 
kind: Service
metadata:
  name: explore
spec:
  template:
    metadata:
        annotations:
          autoscaling.knative.dev/target: '1'
          revisionTimestamp: ''
    spec:
      containers:
      - image: quay.io/guimou/data_explore:latest
        ports:
              - containerPort: 5000
        env:
        - name: model_version
          value: 'v1'
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: AWS_ACCESS_KEY_ID 
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: AWS_SECRET_ACCESS_KEY 
        - name: service_point
          valueFrom:
            configMapKeyRef:
              name: service-point
              key: url
        resources:
          limits:
            cpu: '2'
            memory: 500M
          requests:
            cpu: 400m
            memory: 100M

