apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: oc-update-image-generator-dc
spec:
  inputs:
    params:
      - description: The name of the deployment configuration we want to update
        name: seconds_wait
        type: string
  steps:
    - image: 'quay.io/openshift/origin-cli:latest'
      name: patch-service
      resources: {}
      script: >
        oc patch dc image-generator
        --type=json -p
        '[
          {"op":"replace","path":"/spec/template/spec/containers/0/env/0/value","value":"$(inputs.params.seconds_wait)"}
        ]'