apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: risk-assessment-refresh
spec:
  pipelineRef:
    name: knative-service-risk-assessment-refresh
  params:
    - name: service-name
      value: risk-assessment
    - name: model-version
      value: v1
  serviceAccountName: pipeline
