apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: mysql-grafana-datasource
  namespace: xrayedge
spec:
  datasources:
    - type: mysql
      name: MySQL
      access: proxy
      url: xrayedgedb.xrayedge
      database: xrayedgedb
      user: xrayedgeuser
      password: xrayedgepassword
  name: grafana-mysql-datasource.yaml