apiVersion: v1
kind: ConfigMap
metadata:
  name: service-point
  namespace: xrayedge
data:
  url: 'replace_me'
  url-external: 'replace_me'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-host
  namespace: xrayedge
data:
  url: 'replace_me'