apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: mysql-grafana-datasource
spec:
  datasources:
    - type: mysql
      name: MySQL
      access: proxy
      url: xraylab
      database: xraylabdb
      user: xraylab
      password: xraylab
  name: grafana-mysql-datasource.yaml