apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafana-datasource
spec:
  datasources:
    - basicAuthUser: internal
      access: proxy
      secureJsonData: {}
      name: prometheus
      url: 'https://prometheus-k8s.openshift-monitoring.svc:9091'
      basicAuthPassword: >-
        YfLY7QXaFHvFwz9MEOUG+Gy2Cw6NTHiHqviRg2R2Q6iAWTjAlDCVRIPkf3+M29Vss6PROWV8ShP0yM2aNe+ld2HAJadCoCc6HJVXLqUEUGEt8STe6Ip0H2EP5dd665bkps88bi2pwwrPF0lwX1I6hRVbNd6ruDmqu97AxB4Jv31DIlYMnNkqS0jCWAW7Cw3f5OYyFgh4ui1fuNxqkPRFSOWnjlLr7dAdPh5dI3BDf2J72OapTPpGwAP/6Y0tOOAjQZZ1DLGNW4/eb7SU+8VhrKuq1oMRETXrbp0M5ZVJFsuxF1WBQXdkDHkFOBmGSBVqoT2TnWlcRzKtdywttZ0T
      jsonData:
        timeInterval: 5s
        tlsSkipVerify: true
      basicAuth: true
      version: 1
      type: prometheus
      orgId: 1
  name: grafana-prometheus-datasource.yaml

