apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: ach
stringData:
    AWS_ACCESS_KEY_ID: replace_me     
    AWS_SECRET_ACCESS_KEY: replace_me
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: ach
stringData:
    database-user: replace_me     
    database-password: replace_me
    database-host: replace_me 
    database-db: replace_me 