apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: image-generator-build
spec:
  pipelineRef:
    name: knative-service-build
  resources:
    - name: git-repo
      resourceRef:
        name: xrayedge-repo
    - name: push-image
      resourceRef:
        name: image-generator-image
  params:
    - name: context
      value: './demos/xrayedge/containers/image-generator'
  serviceAccountName: pipeline
