apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: risk-assessment-build
spec:
  pipelineRef:
    name: knative-service-build
  resources:
    - name: git-repo
      resourceRef:
        name: xrayedge-repo
    - name: push-image
      resourceRef:
        name: risk-assessment-image
  params:
    - name: context
      value: './demos/xrayedge/containers/risk-assessment'
  serviceAccountName: pipeline
